### ISSUE TITLE
public.ecr.aws/lambda/python:3.9 incompatible with latest botocore

### ISSUE THREAD

**Issue by thyer** [aws/aws-lambda-base-images#172]
Related to #8 - with botocore introducing changes in auth.py, any docker image using lamba/python:3.9 as a base and adding botocore via `pip` or `poetry` will see the error `Unable to import module 'my_module': cannot import name 'resolve_auth_type' from 'botocore.auth' (/var/runtime/botocore/auth.py)`. This is due to the base image's version of `/var/lang/lib/python3.9/site-packages/botocore/__init__.py` not having the latest changes. 

A minimal repro as follows:
```
FROM public.ecr.aws/lambda/python:3.9
COPY . ${LAMBDA_TASK_ROOT}
RUN pip install awscli
RUN pip install botocore==1.35.7
RUN pip install boto3==1.35.7
CMD ["my_module.handle_request"]
```

Where my_module.handle_request simply calls the [newly added function](https://github.com/boto/botocore/commit/4351aceca018b66f3b63e343ebc4c5ee4f761c6f#diff-93392e4565eff0b6a2f3cb5a9f0e7fbe1e8855fc9d189ae6ed954fd012d65811)
`from botocore.auth import resolve_auth_type`

**Comment by thyer** [comment]
Note that as [mentioned](https://github.com/aws/aws-lambda-base-images/issues/8#issuecomment-1482965914) at the time of the last issue, wiping them from the image is a suitable workaround, but it provides a ticking time bomb for anybody relying on a stable production environment. I would strongly encourage a fix that does not simply bring the latest botocore into the base image, but rather addresses the /var/runtime/ vs. /var/lang/lib/python3.9/ shadowing.

**Comment by jtuliani** [comment]
Hi @thyer . Prior to Python 3.11, /var/runtime took precedence over the site-packages directory. This resulted in the module being loaded from the runtime instead of their pip installation. Switching the base image to Python 3.11 should resolve the issue. For details, see our  [blog post](https://aws.amazon.com/blogs/compute/python-3-11-runtime-now-available-in-aws-lambda/#:~:text=Change%20in%20pre%2Dinstalled%20modules%20location%20and%20search%20path).

Also, from the above, it looks like your module installation didn't copy your pip-installed version into ${LAMBDA_TASK_ROOT}, so your pip-installed version wasn't actually being used.
