### ISSUE TITLE
Glibc 2.17 on python3.7 image. Should be Glibc 2.26.

### ISSUE THREAD

**Issue by patrickodpt** [aws/aws-lambda-base-images#5]
I encountered this error running TF 1.14.0 on `amazon/aws-lambda-python:3.7` :
```
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /var/task/tensorflow/python/_pywrap_tensorflow_internal.so)
```
Inspecting the Glibc version in this running container with `docker exec -it <container> ldd --version ldd` shows `ldd (GNU libc) 2.17`

Per the resource, [AWS Lambda > Developer Guide > Working with Python > Deploy container images ](https://docs.aws.amazon.com/lambda/latest/dg/python-image.html), the image is using the Amazon Linux 2 operating system [which is supposed to come with Glibc 2.26](https://aws.amazon.com/amazon-linux-2/release-notes/).

**Comment by carlzogh** [comment]
Thanks @patrickodpt for reporting this! The Lambda `python3.7` runtime & base image use the Amazon Linux 2018.03 base OS and the documentation was inaccurately suggesting Amazon Linux 2 instead.

This has since been updated to list the base OS for Python 3.7 as Amazon Linux 2018.03 ([link here](https://docs.aws.amazon.com/lambda/latest/dg/python-image.html))

Apologies for the inconvenience this has caused and thanks again for highlighting the issue :)
